version: '3.2'

services:

  web:
    env_file:
      - .env.dev
    build: .
    restart: always
    environment:
      PORT: 5000
      MARKET_BASE: EUR
      MARKETS: ALGO,BTC,ETH,XLM,ZRX
    ports:
      - '5000:5000'

volumes:
  db_data:
