name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: finwo/coinbase-trader
        tag_with_ref: true
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Deploy webhook
      run: 'curl -X POST --header "Authorization: Bearer ${{ secrets.SWARMPIT_TOKEN }}" --header "Content-Type: application/json" --header "Accept: application/json" "https://swarmpit.finwo.net/api/stacks/bittorrent-tracker/redeploy"'
