name: CI

on:
  push:
    branches: [ master ]

jobs:

  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: finwo/coinbase-trader:latest
      #     build-args: |
      #       arg1=value1
      #       arg2=value2

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

  deploy-webhook:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy webhook
        run: 'curl -X POST --header "Authorization: Bearer ${{ secrets.SWARMPIT_TOKEN }}" --header "Content-Type: application/json" --header "Accept: application/json" "https://swarmpit.finwo.net/api/stacks/coinbase-trader/redeploy"'
